config/routes.rb
Rzaartz::Application.routes.draw do

  devise_for :users

  resources :our_works

  mount Ckeditor::Engine => '/ckeditor'

  resources :slides

  namespace :blog do
    root :to => 'posts#index'
    resources :posts
  end
  resources :messages

  root :to => 'welcome#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :title, :post_image
  has_attached_file :post_image, :styles => {:bord => "821x410>"}
  validates_attachment_presence :post_image
  validates_attachment_content_type :post_image, :content_type => ['image/jpeg', 'image/png', 'image/gif']
  validates_attachment_presence :post_image
end

app/controllers/blog/posts_controller.rb
class Blog::PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(params[:post])
    if @post.save
      respond_to do |format|
        format.html {redirect_to blog_post_path(@post)}
      end
    else
      render :new
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(params[:post])
      respond_to do |format|
        format.html {redirect_to blog_post_path(@post)}
      end
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to blog_posts_url
  end
end

app/helpers/blog/posts_helper.rb
module Blog::PostsHelper
end

app/views/blog/posts/_form.html.erb
<%= form_for([:blog, @post]) do |f| %>
    <% if @post.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@post.errors.count, "error") %> prohibited this blog post from being saved:</h2>

          <ul>
            <% @post.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :title %><br />
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :body %><br />
      <%= f.cktext_area :body,  :ckeditor => {:uiColor => "#AADC6E", :toolbar => "mini"} %>
    </div>
    <div class="field">
      <%= f.label :post_image %><br />
      <%= f.file_field :post_image %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/blog/posts/_post.html.erb
<section class="post_outer">
  <article>
    <header>
      <h1 class="entry-title"><a rel="bookmark" title="Maecenas vestibulum faucibus enim vel gravida" href="<%= url_for blog_post_path(post) %>"><%= post.title %></a> </h1>
    </header>
    <div class="entry-content">
      <div class="row-fluid">
        <div class="span12">
          <% if post.post_image.present? %>
          <div class="post-image">
            <p>
              <%= link_to image_tag(post.post_image), blog_post_path(post), class: "alignnone size-full wp-image-4" %></p>
          </div>
          <% end %>
          <div class="post-date">
            <div class="single_dateouter">
              <p>
                <label><%= post.created_at.day %></label>
                <span><%= MONTH[post.created_at.month-1]%></span></p>
            </div>
          </div>
          <div class="post-content">
           <%= raw post.body %>
          </div>
        </div>
      </div>
    </div>
    <footer class="post-footer">
      <p>
        <%= link_to "Edit", edit_blog_post_path(post) %> | <%= link_to "Delete", blog_post_path(post), method: :delete, data: {confirm: "Are you sure"} %>
      </p>
    </footer>
  </article>
</section>

app/views/blog/posts/edit.html.erb
<div class="row-fluid" >
  <div class="span12 blog_section_outer">
    <div class="blog_outer">
      <h3><span>Edit Blog Post</span></h3>
      <div class="row-fluid">
        <!--blog content start-->
        <div class="span9">
          <%= render "form" %>

        </div>
        <!--blog content end-->
        <!--blog sidebar start-->
        <%= render "admin_menu" %>
        <!--blog sidebar end-->
      </div>
    </div>

  </div>
</div>

app/views/blog/posts/index.html.erb
<div class="row-fluid" >
  <div class="span12 blog_section_outer">
    <div class="blog_outer">
      <h3><span>Our Blog</span></h3>
      <div class="row-fluid">
        <!--blog content start-->
        <div class="span9">
          <%= render @posts %>
        </div>
        <!--blog content end-->
        <!--blog sidebar start-->
        <%= render "admin_menu" %>
        <!--blog sidebar end-->
      </div>
    </div>

  </div>
</div>

app/views/blog/posts/new.html.erb
<div class="row-fluid" >
  <div class="span12 about_section_outer">
    <div class="blog_outer">
      <h3><span>New Blog Post</span></h3>
      <div class="row-fluid">
        <!--blog content start-->
        <div class="span9">
          <%= render "form" %>

        </div>
        <!--blog content end-->
        <!--blog sidebar start-->
        <%= render "admin_menu" %>
        <!--blog sidebar end-->
      </div>
    </div>

  </div>
</div>

app/views/blog/posts/show.html.erb
<div class="row-fluid" >
  <div class="span12 blog_section_outer">
    <div class="blog_outer">
      <h3><span><%= @post.title %></span></h3>
      <div class="row-fluid">
        <!--blog content start-->
        <div class="span9">
          <%= render @post %>

        </div>
        <!--blog content end-->
        <!--blog sidebar start-->
        <%= render "admin_menu" %>
        <!--blog sidebar end-->
      </div>
    </div>

  </div>
</div>