config/routes.rb
Rzaartz::Application.routes.draw do

  devise_for :users

  resources :our_works

  mount Ckeditor::Engine => '/ckeditor'

  resources :slides

  namespace :blog do
    root :to => 'posts#index'
    resources :posts
  end
  resources :messages

  root :to => 'welcome#index'

end

app/models/slide.rb
class Slide < ActiveRecord::Base
  attr_accessible :name, :slide_image
  has_attached_file :slide_image, :styles => {:bord => "821x410>"}
  validates_attachment_presence :slide_image
  validates_attachment_content_type :slide_image, :content_type => ['image/jpeg', 'image/png', 'image/gif']
  validates_attachment_presence :slide_image
end

app/controllers/slides_controller.rb
class SlidesController < ApplicationController
  # GET /slides
  # GET /slides.json
  def index
    @slides = Slide.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @slides }
    end
  end

  # GET /slides/1
  # GET /slides/1.json
  def show
    @slide = Slide.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @slide }
    end
  end

  # GET /slides/new
  # GET /slides/new.json
  def new
    @slide = Slide.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @slide }
    end
  end

  # GET /slides/1/edit
  def edit
    @slide = Slide.find(params[:id])
  end

  # POST /slides
  # POST /slides.json
  def create
    @slide = Slide.new(params[:slide])

    respond_to do |format|
      if @slide.save
        format.html { redirect_to @slide, notice: 'Slide was successfully created.' }
        format.json { render json: @slide, status: :created, location: @slide }
      else
        format.html { render action: "new" }
        format.json { render json: @slide.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /slides/1
  # PUT /slides/1.json
  def update
    @slide = Slide.find(params[:id])

    respond_to do |format|
      if @slide.update_attributes(params[:slide])
        format.html { redirect_to @slide, notice: 'Slide was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @slide.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slides/1
  # DELETE /slides/1.json
  def destroy
    @slide = Slide.find(params[:id])
    @slide.destroy

    respond_to do |format|
      format.html { redirect_to slides_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/slides_helper.rb
module SlidesHelper
end

app/views/slides/_form.html.erb
<%= form_for(@slide) do |f| %>
  <% if @slide.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@slide.errors.count, "error") %> prohibited this slide from being saved:</h2>

      <ul>
      <% @slide.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
    <div class="field">
      <%= f.label :slide_image %><br />
      <%= f.file_field :slide_image %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/slides/_slide.erb
<section class="post_outer">
  <h1 class="entry-title">
    <%= slide.name %>
  </h1>
  <div class="post-content">
    <p><%= image_tag slide.slide_image(:bord)%></p>
    <p>
      <%= link_to "Edit", edit_slide_path(slide) %> | <%= link_to "Delete", slide, method: :delete, data: {confirm: "Are you sure"} %>
    </p>

  </div>
</section>

app/views/slides/edit.html.erb
<div class="row-fluid" >
  <div class="span12 blog_section_outer">
    <div class="blog_outer">
      <h3><span>Edit Side</span></h3>
      <div class="row-fluid">
        <!--blog content start-->
        <div class="span9">
          <%= render "form" %>

        </div>
        <!--blog content end-->
        <!--blog sidebar start-->
        <%= render "admin_menu" %>
        <!--blog sidebar end-->
      </div>
    </div>

  </div>
</div>

app/views/slides/index.html.erb
<div class="row-fluid" >
  <div class="span12 blog_section_outer">
    <div class="blog_outer">
      <h3><span>Manage Sides</span></h3>
      <div class="row-fluid">
        <!--blog content start-->
        <div class="span9">
       <%= render @slides %>
        </div>
        <!--blog content end-->
        <!--blog sidebar start-->
        <%= render "admin_menu" %>
        <!--blog sidebar end-->
      </div>
    </div>

  </div>
</div>

app/views/slides/new.html.erb
<div class="row-fluid" >
  <div class="span12 blog_section_outer">
    <div class="blog_outer">
      <h3><span>New Side</span></h3>
      <div class="row-fluid">
        <!--blog content start-->
        <div class="span9">
          <%= render "form" %>

        </div>
        <!--blog content end-->
        <!--blog sidebar start-->
        <%= render "admin_menu" %>
        <!--blog sidebar end-->
      </div>
    </div>

  </div>
</div>

app/views/slides/show.html.erb
<div class="row-fluid" >
  <div class="span12 blog_section_outer">
    <div class="blog_outer">
      <h3><span><%= @slide.name %></span></h3>
      <div class="row-fluid">
        <!--blog content start-->
        <div class="span9">
          <%= render @slide %>

        </div>
        <!--blog content end-->
        <!--blog sidebar start-->
        <%= render "admin_menu" %>
        <!--blog sidebar end-->
      </div>
    </div>

  </div>
</div>