config/routes.rb
Rzaartz::Application.routes.draw do

  devise_for :users

  resources :our_works

  mount Ckeditor::Engine => '/ckeditor'

  resources :slides

  namespace :blog do
    root :to => 'posts#index'
    resources :posts
  end
  resources :messages

  root :to => 'welcome#index'

end

app/models/our_work.rb
class OurWork < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/our_works_controller.rb
class OurWorksController < ApplicationController
  # GET /our_works
  # GET /our_works.json
  def index
    @our_works = OurWork.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @our_works }
    end
  end

  # GET /our_works/1
  # GET /our_works/1.json
  def show
    @our_work = OurWork.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @our_work }
    end
  end

  # GET /our_works/new
  # GET /our_works/new.json
  def new
    @our_work = OurWork.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @our_work }
    end
  end

  # GET /our_works/1/edit
  def edit
    @our_work = OurWork.find(params[:id])
  end

  # POST /our_works
  # POST /our_works.json
  def create
    @our_work = OurWork.new(params[:our_work])

    respond_to do |format|
      if @our_work.save
        format.html { redirect_to @our_work, notice: 'Our work was successfully created.' }
        format.json { render json: @our_work, status: :created, location: @our_work }
      else
        format.html { render action: "new" }
        format.json { render json: @our_work.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /our_works/1
  # PUT /our_works/1.json
  def update
    @our_work = OurWork.find(params[:id])

    respond_to do |format|
      if @our_work.update_attributes(params[:our_work])
        format.html { redirect_to @our_work, notice: 'Our work was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @our_work.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /our_works/1
  # DELETE /our_works/1.json
  def destroy
    @our_work = OurWork.find(params[:id])
    @our_work.destroy

    respond_to do |format|
      format.html { redirect_to our_works_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/our_works_helper.rb
module OurWorksHelper
end

app/views/our_works/_form.html.erb
<%= form_for(@our_work) do |f| %>
  <% if @our_work.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@our_work.errors.count, "error") %> prohibited this our_work from being saved:</h2>

      <ul>
      <% @our_work.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/our_works/_our_works.erb
<div class="row-fluid" id="work_page">
  <div class="span12 work_section_outer">
    <div class="work_outer">
      <h3><span>Recent Works</span></h3>
      <div class="row">
        <div class="span10 offset1 slides">
          <div class="row-fluid">
            <div class="span12">
              <div class="bs-docs-example">
                <div id="myCarousel" class="carousel slide">
                  <!-- Works Items Start -->
                  <div class="carousel-inner">
                    <div class="active item"><img src="img/works/img_01.jpg" alt=""></div>
                    <div class="item"><img src="img/works/img_02.jpg" alt=""></div>
                    <div class="item"><img src="img/works/img_03.jpg" alt=""></div>
                    <div class="item"><img src="img/works/img_04.jpg" alt=""></div>
                    <div class="item"><img src="img/works/img_05.jpg" alt=""></div>
                    <div class="item"><img src="img/works/img_06.jpg" alt=""></div>
                  </div>
                  <!-- Works Items End -->
                  <!-- Works navigation Start -->
                  <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a> <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a> </div>
                <!-- Works navigation End -->
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Our Work End -->

app/views/our_works/edit.html.erb
<h1>Editing our_work</h1>

<%= render 'form' %>

<%= link_to 'Show', @our_work %> |
<%= link_to 'Back', our_works_path %>

app/views/our_works/index.html.erb
<h1>Listing our_works</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @our_works.each do |our_work| %>
  <tr>
    <td><%= link_to 'Show', our_work %></td>
    <td><%= link_to 'Edit', edit_our_work_path(our_work) %></td>
    <td><%= link_to 'Destroy', our_work, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Our work', new_our_work_path %>

app/views/our_works/new.html.erb
<h1>New our_work</h1>

<%= render 'form' %>

<%= link_to 'Back', our_works_path %>

app/views/our_works/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_our_work_path(@our_work) %> |
<%= link_to 'Back', our_works_path %>