config/routes.rb
Rzaartz::Application.routes.draw do

  devise_for :users

  resources :our_works

  mount Ckeditor::Engine => '/ckeditor'

  resources :slides

  namespace :blog do
    root :to => 'posts#index'
    resources :posts
  end
  resources :messages

  root :to => 'welcome#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_admin_menu.html.erb
<% if can? :create, Post %>
<div class="span3">
  <aside class="sidebar">
    <form class="form-search">
      <div class="input-append">
        <input type="text" class="span12 search-query" placeholder="Search Blog">
        <button type="submit" class="btn"><i class="icon-search"></i></button>
      </div>
    </form>
  </aside>
  <!-- Recent Post start-->
  <aside class="sidebar">
    <h2 class="mostpopular">Menu</h2>
    <div class="singlesection">
      <%= link_to "Add new slide", new_slide_path %>
    </div>
    <div class="singlesection">
      <%= link_to "Add Blog Post", new_blog_post_path %>
    </div>
  </aside>
  <!-- Recent Post end-->
</div>

<% end %>

app/views/application/_banner_and_slider.html.erb
<div id="index_page" class="row-fluid">
  <div class="span12 topbanner_section">
    <div class="row-fluid">
      <!-- Logo Area Start -->
      <div class="span12">
        <h1><a href="#"><img src="/assets/company_logo.png" alt="logo"></a></h1>
      </div>
      <!-- Logo Area Start -->
    </div>
    <div class="row-fluid">
      <div class="span12 banner_outer">
        <div id="myCarousel2" class="carousel slide">
          <!-- Slider Items Start -->
          <div class="banner_slides">
            <div class="row-fluid">
              <div class="span12  span_bannercon">
                <div class="carousel-inner">
                  <% @slides.each do |slide| %>
                      <div class="<% if slide == @slides.first %>active <% end %>item">
                        <span class="image_1"><%= image_tag slide.slide_image(:bord)%></span>
                      </div>
                  <% end %>
                </div>

                <!-- Slider navigations Start -->
                <a class="carousel-control left" href="#myCarousel2" data-slide="prev">&lsaquo;</a> <a class="carousel-control right" href="#myCarousel2" data-slide="next">&rsaquo;</a>
                <!-- Slider navigations End -->
              </div>
            </div>
          </div>
          <!-- Sliding Items End -->
        </div>
      </div>
    </div>
  </div>
</div>

app/views/application/_footer.html.erb
<div id="contact_page" class="row-fluid">
  <div class="span12 contact_section_outer">

    <!-- Contact form Start -->
    <div class="contact_outer">
      <h3><span>Reach Us</span></h3>
      <div class="row-fluid">
        <div class="span8 main_formouter">
          <%= form_for Message.new, remote: true do |f| %>
            <div class="contact_message"></div>
            <div class="row-fluid contact_formouter">
              <div class="span6">
                <%= f.text_field :name, placeholder: "Name (Required)", class: "input-xlarge" %>
              </div>
              <div class="span6">
                <%= f.email_field :email, placeholder: "Email (Required)", class: "input-xlarge" %>
              </div>
            </div>
            <div class="row-fluid contact_formouter">
              <div class="span6">
                <%= f.phone_field :phone_number, placeholder: "Phone Number", class: "input-xlarge" %>
              </div>
              <div class="span6">
                <%= f.text_field :subject, placeholder: "Subject (Required)", class: "input-xlarge" %>
              </div>
            </div>
            <div class="row-fluid contact_formouter">
              <div class="span12">
                <%= f.text_area :content, placeholder: "Message (Required)", class: "input-xlarge", rows: 3, style: "height: 100px;" %>
              </div>
            </div>
            <div class="row-fluid contact_formouter">
              <div class="span12">
                <button class="btn btn-inverse" type="submit">Submit</button>
              </div>
            </div>
          <% end %>
        </div>
        <div class="span4 contact_right">
          <!-- Call Us -->
          <div class="contact_single">
            <div class="contact_single_left">
              <div class="contact_single_iconouter"><span class="icon-phone"></span></div>
            </div>
            <div class="contact_single_right">
              <h5>Call Us</h5>
              <p>+2348163453879<br>
                +2348163453879</p>
            </div>
          </div>
          <!-- Call Us -->
          <!-- Email Address -->
          <div class="contact_single">
            <div class="contact_single_left">
              <div class="contact_single_iconouter"><span class="icon-envelope"></span></div>
            </div>
            <div class="contact_single_right">
              <h5>Email Addresses</h5>
              <p><a href="#">rzaartz@gmail.com</a><br>
                <a href="#">rzaartz@yahoo.com</a></p>
            </div>
          </div>
          <!-- Email Address -->
          <!-- 24x7 Support -->
          <div class="contact_single">
            <div class="contact_single_left">
              <div class="contact_single_iconouter"><span class="icon-cogs"></span></div>
            </div>
            <div class="contact_single_right">
              <h5>24x7 Support</h5>
              <p>Support centre</p>
            </div>
          </div>
          <!-- 24x7 Support -->
        </div>
      </div>
    </div>
    <!-- Contact form End -->
  </div>
</div>
<!-- Reach Us End -->


<!-- Footer Copyright start -->
<div class="row-fluid">
  <div class="span12 copyright_section_outer">
    <div class="copyright_outer">
      <div class="row-fluid">
        <div class="span4"><a href="#"><img src="/assets/footer_logo.png" alt="Logo"></a></div>
        <div class="span4 social_icons">
          <ul>
            <li><a href="#"><span class="icon-facebook"></span></a></li>
            <li><a href="#"><span class="icon-twitter"></span></a></li>
            <li><a href="#"><span class="icon-google-plus"></span></a></li>
          </ul>
        </div>
        <div class="span4 copyright">
          <p>Rzaartz Ltd | RC No: 980521 </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/application/_header_menu.html.erb
<div class="row-fluid">
  <div class="span12">
    <header class="header">
      <!-- Top Navigation Start -->
      <div class="nav">
        <div class="mobile-nav"></div>
        <ul class="primary">
          <% if controller_name == "welcome" %>
          <li id="section_1" class="current"><a href="#index_page" id="1">Home</a></li>
          <li id="section_2" class="" ><a href="#about_page" id="2">About Us</a></li>
          <li id="section_3" class="" ><a href="#service_page" id="3">Services</a></li>
          <li id="section_4" class="" ><a href="#work_page" id="4">Our Works</a></li>
          <li id="section_5" class="" ><a href="#contact_page" id="5">Reach Us</a></li>
          <% else %>
              <li id="section_1"><a href="<%= url_for root_url %>#index_page" id="1">Home</a></li>
              <li id="section_2" class="" ><a href="<%= url_for root_url %>#about_page" id="2">About Us</a></li>
              <li id="section_3" class="" ><a href="<%= url_for root_url %>#service_page" id="3">Services</a></li>
              <li id="section_4" class="" ><a href="<%= url_for root_url %>#work_page" id="4">Our Works</a></li>
              <li id="section_5" class="" ><a href="<%= url_for root_url %>#contact_page" id="5">Reach Us</a></li>
          <% end %>
          <li><a class="has-drop">Blog</a>
            <ul class="drop">
              <li class="current"><%= link_to "Blog", blog_root_url %></li>
            </ul>
          </li>

        </ul>
        <div class="clear"></div>
      </div>
      <!-- Top Navigation End -->
    </header>
  </div>
</div>